### ISSUE TITLE
Feature request: Using several trigger types in conditions

### ISSUE THREAD

**Issue by Sundava** [lichie567/XIVAuras#13]
I would like to be able to use the `Value` from a `Buff` trigger type in the trigger conditions of an aura with a `Cooldown` trigger type.

The use case would be disable the `Riddle of fire CD` cooldown if the buff is UP. 
Current workaround is to add a `Value < (Max CD - Buff duration)` in the conditions for `Riddle of fire CD`, but that seems a bit wonky since the buff does not trigger exactly on button press.

This also makes the `CD` and the `Buff up` conflict, in the case of spells with multiple stacks like Riddle of Earth

**Comment by lichie567** [comment]
I've been taking a break from development before endwalker, so I apologize for taking a while to respond to this. I plan to implement all of this at some point after endwalker is out and I've finished MSQ and leveling my main jobs. I'll be re-working the entire triggering system to make it a lot more powerful.
