### ISSUE TITLE
Feature request: dynamic icon handling per group

### ISSUE THREAD

**Issue by joyvanderveeken** [lichie567/XIVAuras#17]
Currently, if you've got a group set up, all icons have their specific offset within the group. If you only show abilities that are (not) on cooldown, you'd have gaps as soon as an ability is in a different state. 

Similarly to how DelvUI handles auras, it'd be great if icons could be handled dynamically per group. This way, users would not have to offset icons individually, but instead can use padding and group size to adjust the way their icons are shown. 

For example, if a user only shows abilities that are on cooldown (or those that aren't on cooldown), these could be anchored to a specific point and grow from there, so no gaps appear inbetween the icons.

**Comment by Rhae-Dev** [comment]
If the developer doesn't have time for this, I have been thinking about making the modification and offer up a pull request to implement this as it is something I would like as well, just found this mod today and would be almost perfect with this change.
