### ISSUE TITLE
[BUG] Name tag not showing

### ISSUE THREAD

**Issue by Sythalin** [lichie567/XIVAuras#22]
When attempting to create player name labels, the names do not show.

With Standard Text:
![standard text](https://user-images.githubusercontent.com/4165258/150818121-0a56d871-0eb5-41e4-8557-5653fe530541.png)

With [name] Tag:
![name tag](https://user-images.githubusercontent.com/4165258/150818252-df2092d0-ca2c-4fbb-bc3e-cff6b9f95ffe.png)

**Comment by lichie567** [comment]
The [name] text tag will only work if you are using a CharacterState trigger and that trigger is selected as the trigger data source.
