### ISSUE TITLE
After most recent update decimals changes on the X and Y-axis don't save.

### ISSUE THREAD

**Issue by Vinnreo** [lichie567/XIVAuras#26]
After updating the plugin to the most recent version all my icons weren't in the right position anymore. I deleted all the icons I had made and started from scratch and the issue I've noticed is that randomly the decimals on the X and Y axis for the position get rounded up or down, basically making it impossible to have pixel perfect ui. Because of limitations in the game itself, you have to bend certain icons to make them look correct, and with this issue that basically becomes impossible.

**Comment by lichie567** [comment]
You'll have to describe a repeatable way to reproduce this, because after trying for a while I was not able to reproduce this problem.
