### ISSUE TITLE
Monk group + resources

### ISSUE THREAD

**Issue by Essidia** [lichie567/XIVAuras#29]
two things

1. could you share the Monk group from the sample recording as a starting point for the less experienced?
2. Would it be possible to track resources on allies, like addersgall, lilies, aetherflow ? I'm mostly interested in cohealer resources but the q is general.

**Comment by vond82** [comment]
1. Check delvui profiles on wago.io, the most popular ones also have XIVAuras to download that you can look at as a building point
2. Not until gauge is available as a resource, even then you'd need to have your co-healer targeted/focused for it to ever work most likely

**Comment by Essidia** [comment]
Thanks
