### ISSUE TITLE
[Suggestion] Sound cues

### ISSUE THREAD

**Issue by seathasky** [lichie567/XIVAuras#31]
Add sound queues, notifications etc to XIV Auras just like Weakauras has.

**Comment by Iaotle** [comment]
Cues*

**Comment by seathasky** [comment]
> Cues*

![eew9p](https://user-images.githubusercontent.com/17598024/154060521-749f93fd-9cc6-402d-b47d-816f455666ab.jpg)
= english

**Comment by Sythalin** [comment]
Was just coming here to suggest this.  This in combination with the coming timer bars would let me stop spending hours configuring SPESPE for my jobs (i.e. all of them).

**Comment by Sythalin** [comment]
> The config process is so bad that I just gave up tbh

It's really is, but after I figured it out everything is mostly creating duplicates of existing.  The actual UI to do so, however, yeah.... it's terrible.
