### ISSUE TITLE
Auras dissapear when progress bar is present

### ISSUE THREAD

**Issue by Justnich** [lichie567/XIVAuras#46]
Any and all auras i set up become invisible whenever im in the middle of casting something. They work normally otherwise, but its kindve annoying. https://i.gyazo.com/d9ae74699c0eb491654451493c526418.mp4

**Comment by PuckAlive** [comment]
If the trigger you're implementing to show the aura is "Action Usable", they will disappear when you cast because they are not usable while casting. The solution is to add an "or" trigger for  when the cooldown is below whatever threshold time you want.
