### ISSUE TITLE
Summoner Energy Drain cooldown triggers don't work properly

### ISSUE THREAD

**Issue by tizubythefizo** [lichie567/XIVAuras#56]
It looks as though Energy Drain isn't read correctly.

With a trigger set to show when cooldown is < 8 seconds, it will always show (and will not show the swipe or time remaining at all) whether or not its on cooldown.

Steps to reproduce:

1. Set up a trigger on summoner, cooldown - energy drain - < or <= 8
2. Enter combat, cast Energy Drain.

Expected: Energy drain aura does not show until less than 8 seconds remain on its recast timer, and shows up with the swipe and remaining seconds once that is true.

Actual: It just stays solid.

Below is the trigger string for how I've got it set up.

xFHNSsNAEH4VGTwuIVVrQ24lFSyoBVuLUHqYJts0Nt0Nuxu0iE/mwUfyFZzNf6UeBMHkkpnvL3zz+f7xCqdmn3Hw4XE8H+YKtRNIsU5iZ6aSOOaqnIDBCA1WO/BdBtX3JDOJFBr8xc9WgZRpJJ9FLW/Ed7iz/CvBVbw/GSlMBIGB3K3QzAovChpGT7k24K8x1dyipRn4RuWdeZKBf9aOc0xz0nsOOQQbVDEPZC46Nu3OKs8PNpXYLcT0N7KTTlMNM3jQuEp5g5ZjC9+jIMcND7cNpVi1jBupD3FatCj1FyW237LxopEeg6nMVVgyqiLtcY6f4JqnGVfa6RIZHC9+HJH95YA+QhvZ710wuMWXqcFwSxeuy7C0xfLbnd7Yn4T3Xe8f4wf01PED7zfxS3q/AAAA//8DAA==

**Comment by smashmaster1129** [comment]
Having the same issue. From what I could tell, it will always read Energy Drain as having 0 cooldown.
