### ISSUE TITLE
Adoption Request

### ISSUE THREAD

**Issue by WesBosch** [lichie567/XIVAuras#71]
Hi lichie,
I understand that this plugin has been officially abandoned. I'd like to ask for your consent to adopt the project. I wasnt really sure what the best way to contact you was, so I hope this is alright. Currently, I have everything in a working state for the current patch, and I've expanded upon the bars feature you had started on. I've been able to add working bars; both horizontal and vertical, squared and rounded, as well as multiple color options with reversable fill options and automatic in-group sorting. Among other smaller updates. I am a beginner to all of this, so I am learning as I go, but I hope to add more features as well.

In addition to adding new features and maintaining the project, I'd also like to possibly run it by the XIVLauncher PAC for first party support, so I've renamed my fork to something that doesn't reference Auras. (That seemed to be their only issue with it when I asked) I understand completely if this is something you are not comfortable with, in which case I'll keep the fork to myself, but I value your input none-the-less.

Thank you for your time and consideration!
- Wisteria

https://github.com/WesBosch/ReBuff

**Comment by Cellane** [comment]
@WesBosch 
Apologies, I would have commented on your repository but it doesn't have issues opened, so this is the only way I can think of reaching you.

First of all, thank you so much if you're willing to take over the development of XIVAuras! It would be such a loss if the plug-in was lost to the community…

I see that you have already updated the plug-in for patch 6.4 (wow!), but while GitHub says that the latest version is 0.3.0.1, Dalamud still only shows 0.3.0.0. Perhaps the `repo.json` file also needs to be updated?

**Comment by WesBosch** [comment]
Ah yes, I can fix that right away. I'm still new to using github for this as I'm usually just building locally for myself. Still trying to figure out that mystery!

Anyways, it should be good now. I'll see if I can get the issues tab enabled as well
