### ISSUE TITLE
Update status for patch 6.4

### ISSUE THREAD

**Issue by Krojack** [lichie567/XIVAuras#73]
Is this still maintained? If so I'll wait, no rush. If it isn't then I'll look uninstall and look for some replacement.

**Comment by FalconWraith** [comment]
The original developer is not updating the plugin anymore. Tischel is making it compatible with new patches but isn't actively developing any new features or fixing bugs. There's more information in the Discord server about it. 
I think someone else is working on a different fork of the project with a new name.
You can get Tischel's "official" update from their repo: https://raw.githubusercontent.com/Tischel/XIVAuras/main/repo.json

**Comment by zenrar** [comment]
XIVAura doesn't work anymore, even with your link. It is forked by WesBosch and is now called "ReBuff", which does work and is also compatible with XIVAura's configs.

https://github.com/WesBosch/ReBuff/raw/main/repo.json
