### ISSUE TITLE
[04.06.2024] XIV Auras outdated error message

### ISSUE THREAD

**Issue by KonanHarana** [lichie567/XIVAuras#74]
Hello Community,

I am currently installing FFMods on my new PC. However I cant install XIVAuras via Dalamund because it states:
"THis plugin is outdated and incompatible. Please wait for it to be updated by its author"

Is this project still running? Ive seen not that much activity here so I am wondering if I can use this feature in the future or if its currently not actively supported by anyone :)

Many Thanks!

**Comment by FalconWraith** [comment]
XIVAuras has been dead for about a year now. It's been picked up by Tischel and rebranded to DelvCD. https://github.com/DelvUI/DelvCD
